### ISSUE TITLE
proxy-lb readの結果の"Rules"がルールを設定しているにも関わらず空配列となる

### ISSUE THREAD

**Issue by syguer** [sacloud/usacloud#1067]
## 発生している事象

`usacloud proxy-lb read $ID` の実行結果の `Rules` 項目が、ルールを設定されている空配列となる
（webコンソール上ではルールが存在している状態）

## usacloudのバージョン
```
$ usacloud --version
1.13.0 darwin/arm64, build xxxxxx
```

## 動作環境

ご利用の環境をここに記載してください。
記載する内容は以下の通りです。

* OS
  * MacOS
* OSのバージョン
  * 13.4.1
* アーキテクチャ(386/x64/arm等)
  * arn 

## 表示されたエラーメッセージ
エラーメッセージはなく、アクセス自体は成功した結果になります(一部マスクさせていただいております)
```
[
    {
        "Availability": "available",
        "BackendHttpKeepAlive": null,
        "BindPorts": [],
        "CreatedAt": "2023-08-30T20:29:59+09:00",
        "Description": "",
        "FQDN": "",
        "Gzip": {
            "Enabled": false
        },
        "HealthCheck": {
            "DelayLoop": 10,
            "Host": "",
            "Path": "",
            "Protocol": "tcp"
        },
        "ID": [MASKED],
        "IconID": 0,
        "LetsEncrypt": null,
        "ModifiedAt": "2023-08-30T20:29:59+09:00",
        "Name": "[MASKED]",
        "Plan": 100,
        "ProxyNetworks": [
            "[MASKED]"
        ],
        "ProxyProtocol": {
            "Enabled": false
        },
        "Region": "[MASKED]",
        "Rules": [],
        "Servers": [
            {
                "Enabled": true,
                "IPAddress": "[MASKED]",
                "Port": 80,
                "ServerGroup": "group1"
            },
            {
                "Enabled": true,
                "IPAddress": "[MASKED]",
                "Port": 80,
                "ServerGroup": "group2"
            }
        ],
        "SettingsHash": "[MASKED]",
        "SorryServer": {
            "IPAddress": "",
            "Port": 0
        },
        "StickySession": {
            "Enabled": false,
            "Method": ""
        },
        "Syslog": {
            "Port": 514,
            "Server": ""
        },
        "Tags": [],
        "Timeout": {
            "InactiveSec": 10
        },
        "UseVIPFailover": false,
        "VirtualIPAddress": "[MASKED]"
    }
]
```

## その他、補足事項
現在のデータが取得できていないので試せていないのですが、updateで"Plan"を指定した場合も反映されないのでは、と懸念しております

**Comment by syguer** [comment]
@yamamoto-febc
度々申し訳ありません。ご対応いただけますと幸いです

**Comment by yamamoto-febc** [comment]
ご連絡ありがとうございます。

まず「Rulesが空配列になる」についてこちらの手元で再現を試みていますが現状再現できておりません。
まだ数パターンしか試せていないためもう少し調査してみます。

次にupdateでPlanを指定した場合ですが、今回お問い合わせいただいた症状とは別の要因だと思いますが `--plan`を指定すると以下のようなエラーが出る場合があるようでした。

```
$ usacloud proxy-lb update --plan 500 $ID

failed to apply the filter: key 0x140008c99d0 not found in proxylb_plan
```

こちらについては修正します。

**Comment by yamamoto-febc** [comment]
`failed to apply the filter ~`エラーが出る問題については #1068 にて修正を行います。

また、こちらで再現確認を行う中で、プランが空配列になる問題の再現ができました。
こちらについてはルールがない状態からコントロールパネル(webコンソール)上でルール追加後に「反映」ボタンを押していないとこの状態になりました。

もしこちらに該当するようであれば反映ボタンを押してから再度お試しいただければと思います。

**Comment by syguer** [comment]
> また、こちらで再現確認を行う中で、プランが空配列になる問題の再現ができました。
> こちらについてはルールがない状態からコントロールパネル(webコンソール)上でルール追加後に「反映」ボタンを押していないとこの状態になりました。
> 
> もしこちらに該当するようであれば反映ボタンを押してから再度お試しいただければと思います。

本件ご指摘の通り「反映」ができていない状態でした。大変失礼しました。
見つけていただいたエラーの修正ありがとうございます。お忙しい中ご対応ありがとうございました。
本件はcloseとさせてください。
