### ISSUE TITLE
Disk 情報に含まれる "Storage" の情報から Name を取得したい

### ISSUE THREAD

**Issue by yokogawa-k** [sacloud/usacloud#273]
`usacloud disk ls -out json` や `usacloud disk read -out json disk_name`  で表示される情報にそれぞれのディスクを提供している「さくらのクラウド」のストレージサーバと思われる情報の以下のような **Storage** があると思います。
```json
    "Storage": {
      "Class": "iscsi1204",
      "ID": 210019XXXX
    },
```
現在、こちらには **Class** と **ID** しか含まれていないようですが、**Name** を追加していただけませんでしょうか。
[APIサンプル](https://developer.sakura.ad.jp/cloud/api/1.1/disk/#get_disk) や手元で API を確認する限りは Class などと同様に提供されているようです。

```json
    "Storage":{
      "ID":XXXXXXXXXXXXX,
      "Class":"iscsi1204",
      "Name":"Storage Name",
      "Description":"",
```

## 背景

「さくらのクラウド」にてディスクの障害が発生した際に、[メンテナンス・障害情報・機能追加｜さくらインターネット公式サポートサイト](http://support.sakura.ad.jp/mainte/mainteentry.php?id=22809) のような内容が出るのですが、この中で提供される情報は以下のようになっています。
> 影響範囲 : さくらのクラウド 石狩第1ゾーン 20GB SSDプランストレージ
 sac-is1a-ssd20g-st24

このストレージ名から影響のあったディスクを調べたいと考えています。
この場合、想定している使い方としては以下のような感じです

```console
$ usacloud disk ls -out json | jq -r '.[] | select(.Storage.Name == "sac-is1a-ssd20g-st24") |(.ID|tostring) + ": " + .Name'
112901589XXX: disk_name
```

`libsacloud/sacloud/disk.go` の変更だけで良いのかわからなかったので PullRequest ではなく Issue でのお願いになってしまいました。申し訳ありません。

**Comment by yamamoto-febc** [comment]
ありがとうございます！
記載いただいたユースケースは非常に有用だと思います。

`Storage`配下の情報を追加する対応を行います！

**Comment by yamamoto-febc** [comment]
#274 にて対応しました。
次のリリースに含めますので、リリースまで今しばらくお待ちください:bow:

**Comment by yokogawa-k** [comment]
素早いご対応ありがとうございます :bowing_man:
