### ISSUE TITLE
Debian Busterでapt installできない

### ISSUE THREAD

**Issue by higebu** [sacloud/usacloud#515]
## 発生している事象

* GPG関連のエラーで、Debian buster及びtestingで apt install できない

## usacloudのバージョン

インストール前です

## 動作環境

ご利用の環境をここに記載してください。
記載する内容は以下の通りです。

* OS: Debian
* OSのバージョン: buster / testing
* アーキテクチャ(386/x64/arm等): x64

## 表示されたエラーメッセージ

```
W: GPG error: https://releases.usacloud.jp/usacloud/repos/debian  Release: Detached signature file '/var/lib/apt/lists/partial/releases.usacloud.jp_usacloud_repos_debian_Release.gpg' is in unsupported binary f
ormat
E: The repository 'https://releases.usacloud.jp/usacloud/repos/debian  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

## その他、補足事項

* 福井高専の方のブログの内容も同様の事象のようです。 https://www.ei.fukui-nct.ac.jp/2020/01/06/usacloud/

**Comment by yamamoto-febc** [comment]
ご報告ありがとうございます!
 手元の環境でも再現できました。修正します。

**Comment by yamamoto-febc** [comment]
https://github.com/sacloud/docker-util-images/pull/1 でリリース時のGPG署名処理を修正しました。
usacloudのインストールスクリプトが利用するaptリポジトリ `https://releases.usacloud.jp/usacloud/repos/debian/`に反映済みです。

また問題が発生するようであれば再オープンしてください。
