### ISSUE TITLE
NFSアプライアンスの作成で20GBのプランを選択できるようにして欲しい

### ISSUE THREAD

**Issue by tar-xzvff** [sacloud/usacloud#524]
## 発生している事象

usacloud nfs create実行時に、選択可能なplanの中に20GB(20)が含まれていないため20GBプランのNFS作成ができない。
## usacloudのバージョン

利用中のusacloudのバージョンをここに記載してください。

以下のコマンドを実行すると、現在ご利用中のバージョンを表示できます。

```
usacloud version 0.31.0 linux/amd64, build 97bc3ae
```

## 動作環境

Usacloud SandBox
## 表示されたエラーメッセージ

```
[Options] : "--size": must be in [100,500,1024,2048,4096,8192,12288]
```

## その他、補足事項

その他、補足事項などがあれば、ここに記載してください

**Comment by yamamoto-febc** [comment]
ご報告ありがとうございます。usacloud v0系/v1系両方で20GBのプランを選択できるように対応します。

**Comment by yamamoto-febc** [comment]
Usacloud v0.34.2にて対応しました。
https://github.com/sacloud/usacloud/releases/tag/v0.32.4

**Comment by tar-xzvff** [comment]
早速使わせていただきました、無事作成できました。
ご対応ありがとうございます。

**Comment by yamamoto-febc** [comment]
v0/v1ともに対応済みなためクローズ
